apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hzun1ol1o-python
  janus-idp.io/tekton: hzun1ol1o-python
  backstage.io/kubernetes-id: hzun1ol1o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hzun1ol1o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
